# Start flavours
# Base16 tender 256 - alacritty color config
# Jacobo Tabernero (https://github/com/jacoborus/tender.vim)
[[colors.indexed_colors]]
color = "0xdc9656"
index = 16

[[colors.indexed_colors]]
color = "0xa16946"
index = 17

[[colors.indexed_colors]]
color = "0x383838"
index = 18

[[colors.indexed_colors]]
color = "0x484848"
index = 19

[[colors.indexed_colors]]
color = "0xb8b8b8"
index = 20

[[colors.indexed_colors]]
color = "0xe8e8e8"
index = 21

[colors.bright]
black = "0x4c4c4c"
blue = "0xb3deef"
cyan = "0x73cef4"
green = "0xc9d05c"
magenta = "0xd3b987"
red = "0xf43753"
white = "0xfeffff"
yellow = "0xffc24b"

[colors.cursor]
cursor = "0xeeeeee"
text = "0x282828"

[colors.normal]
black = "0x282828"
blue = "0xb3deef"
cyan = "0x73cef4"
green = "0xc9d05c"
magenta = "0xd3b987"
red = "0xf43753"
white = "0xeeeeee"
yellow = "0xffc24b"

[colors.primary]
background = "0x282828"
foreground = "0xeeeeee"
# End flavours

[font]
size = 12.0

[font.normal]
family = "FiraCode Nerd Font"

[window]
decorations = "full"
opacity = 0.8

[window.padding]
x = 5
y = 5
