version: 2

updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
      day: monday
    open-pull-requests-limit: 10

  # Maintain dependencies for Git Submodules
  - package-ecosystem: gitsubmodule
    directory: /
    schedule:
      interval: monthly
      day: monday
    open-pull-requests-limit: 10
