version: 2

updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    cooldown:
      default-days: 7
    commit-message:
      prefix: ci
      include: scope
    open-pull-requests-limit: 10

  # Maintain dependencies for Git Submodules
  - package-ecosystem: gitsubmodule
    directory: /
    schedule:
      interval: monthly
    cooldown:
      default-days: 7
    commit-message:
      prefix: chore
      include: scope
    open-pull-requests-limit: 10
