#!/bin/bash

set -euo pipefail

# Credits:
# https://github.com/Misterio77/dotfiles/blob/sway/home/.config/waybar/config.json

THEME=$(flavours current)
# shellcheck disable=SC2312
flavours list -l | alacritty-fzf --preview='flavours apply -l {}' || flavours apply "${THEME}"
# shellcheck disable=SC2312
flavours apply "$(flavours current)"
