#!/bin/bash

# Left click
if [[ "${BLOCK_BUTTON}" -eq 1 ]]; then
# Alsa:
  amixer -q sset Master 5%+
# Pulseaudio:
#  amixer -D pulse sset Master 4%+
# Middle click
elif [[ "${BLOCK_BUTTON}" -eq 2 ]]; then
# Alsa:
  amixer -q sset Master toggle
# Pulseaudio:
#  amixer -q -D pulse sset Master toggle
# Right click
elif [[ "${BLOCK_BUTTON}" -eq 3 ]]; then
# Alsa:
  amixer -q sset Master 5%-
# Pulseaudio:
#  amixer -D pulse sset Master 4%-
# Scroll up
elif [[ "${BLOCK_BUTTON}" -eq 4 ]]; then
# Alsa:
  amixer -q sset Master 1%+
# Pulseaudio:
#  amixer -D pulse sset Master 1%+
# Scroll down
elif [[ "${BLOCK_BUTTON}" -eq 5 ]]; then
# Alsa:
  amixer -q sset Master 1%-
# Pulseaudio:
#  amixer -D pulse sset Master 1%-
fi



statusLine=$(amixer get Master | tail -n 1)
status=$(echo "${statusLine}" | grep -wo "on")
volume=$(echo "${statusLine}" | awk -F ' ' '{print $5}' | tr -d '[]%')

if [[ "${status}" == "on" ]]; then
  echo "${volume}%"
  echo "${volume}%"
  #echo ""
else
  echo "MUTE"
  echo "MUTE"
  #echo ""
fi
