name: Pull Request or Push to master

on:
  pull_request: {}
  push:
    branches: [master]
  workflow_dispatch: {}

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

permissions: {}

jobs:
  trunk_check:
    name: Trunk Check
    runs-on: ubuntu-latest
    permissions:
      checks: write # For Trunk to post annotations
      contents: read
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - name: Trunk Check
        uses: trunk-io/trunk-action@f6c5f1b90503c30e02059667dbc247f2257b63c5 # v1.1.15
