name: Pull Request or Push to master

on:
  pull_request: {}
  push:
    branches: [master]
  workflow_dispatch: {}

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

permissions: {}

jobs:
  trunk_check:
    name: Trunk Check
    runs-on: ubuntu-latest
    permissions:
      checks: write # For Trunk to post annotations
      contents: read
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6
      - name: Trunk Check
        uses: trunk-io/trunk-action@540e7fe497a45ae76370d26d95cc249059c4ac3a # v1.1.12
